# Generated by Django 5.0.4 on 2024-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='username',
            field=models.CharField(default='unknown_user', max_length=150),
        ),
    ]
